*** Variables ***

# Variables

${MAINPAGE_TITLE}  Restaurant Order Application
${MAINPAGE_HEADER_TEXT}  Main Page

# Locators

${MAINPAGE_ID}  id=MainPageWindow
${MAINPAGE_HEADER_ID}  id=MainPageTitle
${MAINPAGE_NEXT_ID}  id=NextButton
${MAINPAGE_PREVIOUS_ID}  id=PreviousButton
${MAINPAGE_TABCONTROL}  id=MainPageTabControl
${MAINPAGE_ORDER_TAB}  Order Tab
${MAINPAGE_SUMMARY_TAB}  Summary Tab

# Order Tab Locators

${MAINPAGE_MENU_ID}  id=MainPageMenu
${MAINPAGE_ORDER_TAB_DRINK_LISTBOX}  id=DrinkListBox
${MAINPAGE_ORDER_TAB_DISHES_LISTBOX}  id=DishesListBox
${MAINPAGE_ORDER_TAB_AVAILABLE_DATE_CALENDAR}  id=AvailableDateCalendar
${MAINPAGE_ORDER_TAB_AVAILABLE_DATE_TEXTBOX}  id=AvailableDateTextBox
${MAINPAGE_ORDER_TAB_BANANA_DESSERT_RADIOBUTTON}  id=BananaDessertRadioButton
${MAINPAGE_ORDER_TAB_WATERMELON_DESSERT_RADIOBUTTON}  id=WatermelonDessertRadioButton
${MAINPAGE_ORDER_TAB_PINEAPPLE_DESSERT_RADIOBUTTON}  id=PineappleDessertRadioButton
${MAINPAGE_ORDER_TAB_GUAVA_DESSERT_RADIOBUTTON}  id=GuavaDessertRadioButton
${MAINPAGE_ORDER_TAB_MANGO_DESSERT_RADIOBUTTON}  id=MangoDessertRadioButton
${MAINPAGE_ORDER_TAB_ORANGE_DESSERT_RADIOBUTTON}  id=OrangeDessertRadioButton
${MAINPAGE_ORDER_TAB_ICE_CREAM_DESSERT_RADIOBUTTON}  id=IceCreamDessertRadioButton
${MAINPAGE_ORDER_TAB_YAOURT_DESSERT_RADIOBUTTON}  id=YaourtDessertRadioButton
${MAINPAGE_ORDER_TAB_TOP_SEAT_VIEW_TOGGLEBUTTON}  id=SeatViewTopToggleButton
${MAINPAGE_ORDER_TAB_BOTTOM_SEAT_VIEW_TOGGLEBUTTON}  id=SeatViewBottomToggleButton
${MAINPAGE_ORDER_TAB_LEFT_SEAT_VIEW_TOGGLEBUTTON}  id=SeatViewLeftToggleButton
${MAINPAGE_ORDER_TAB_RIGHT_SEAT_VIEW_TOGGLEBUTTON}  id=SeatViewRightToggleButton
${MAINPAGE_ORDER_TAB_CENTER_SEAT_VIEW_TOGGLEBUTTON}  id=SeatViewCenterToggleButton
${MAINPAGE_ORDER_TAB_DATE_PERSON_COMBOBOX}  id=DatePersonCombobox
${MAINPAGE_ORDER_TAB_OPTIONAL_REQUESTS_EXPANDER}  id=OptionalRequestExpander
${MAINPAGE_ORDER_TAB_ARRIVE_LATE_OPTIONAL_REQUESTS_CHECKBOX}  id=ArriveLateOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_ARRIVE_EARLY_OPTIONAL_REQUESTS_CHECKBOX}  id=ArriveEarlyOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_MORE_SEAT_OPTIONAL_REQUESTS_CHECKBOX}  id=MoreSeatOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_MORE_DRINK_OPTIONAL_REQUESTS_CHECKBOX}  id=MoreDrinkOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_MORE_DISHES_OPTIONAL_REQUESTS_CHECKBOX}  id=MoreDishesOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_CHANGE_DATE_PERSON_OPTIONAL_REQUESTS_CHECKBOX}  id=ChangeDatePersontOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_CHANGE_SEAT_VIEW_OPTIONAL_REQUESTS_CHECKBOX}  id=ChangeSeatViewOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_CHANGE_DESSERT_OPTIONAL_REQUESTS_CHECKBOX}  id=ChangeDessertOptionalRequestCheckBox
${MAINPAGE_ORDER_TAB_GUIDELINE_TREEVIEW}  id=GuidelineTreeView
${MAINPAGE_ORDER_TAB_REGULAR_CUSTOMER_REGISTER_BUTTON}  id=RegularCustomerRegisterButton
${MAINPAGE_ORDER_TAB_RATE_SLIDER}  id=RateSlider
${MAINPAGE_ORDER_TAB_RATE_SCORE_TEXTBOX}  id=RateScoreTextBox
${MAINPAGE_ORDER_TAB_CHANGE_WINDOW_COLOR_BUTTON}  id=ChangeWindowColorButton
${MAINPAGE_ORDER_TAB_PERSON_DATETIME_PICKER}  id=PersonDatePicker

# Summary Tab Locators

${MAINPAGE_SUMMARY_TAB_TABLE}  id=dgUsers

# Register Dialog  Locators

${REGISTER_DIALOG_TITLE}  Regular Customer Information
${REGISTER_DIALOG_ID}  id=RegisterDialogWindow
${REGISTER_DIALOG_NAME_TEXTBOX}  id=CustomerNameTextBox
${REGISTER_DIALOG_BIRTHDAY_TEXTBOX}  id=CustomerBirthdayTextBox
${REGISTER_DIALOG_OK_BUTTON}  id=RegisterDialogOKButton
${REGISTER_DIALOG_CANCEL_BUTTON}  id=RegisterDialogCancelButton
